name: The Survival Games
main: com.communitysurvivalgames.thesurvivalgames.TheSurvivalGames
version: 1.0.0
author: The Community!
database: true

commands:
    sg: 
        usage: /sg <command>
        description: Base command for all SG related functions
        aliases: [survival-games, sgames, hg] 
    party:
        usage: /party <command>
        description: Base command for all party related functions
        aliases: [team, p] 
permissions:
    sg.admin:
        description: Gives access to all SG commands.
        #command: This right? =P
        children:
        - sg.mod
        - sg.user
        - sg.create
        - sg.gamestate.*
        #Rest indev
